### PR TITLE
Update docs for "work update" API

### PR DESCRIPTION
**Pull request by babbtx**

### CODE REVIEW

**Comment by babbtx** [comment]
Good catch. I updated it.

**Comment by msgerbush** [comment]
Do we need the `ticket_id` to update a work object?  Seems like work object id will be enough, and is more consistent with how we treat associated objects elsewhere.

On the JSON response, what's the difference between `labor` and `rate`?

**Comment by babbtx** [comment]
Yeah, we don't need it. I'm not too strong of an opinion either way. You want me to remove it I can do that pretty easily.

**Comment by babbtx** [comment]
The difference between labor and rate would be more apparent if the time spent wasn't an hour. Labor is the product of rate and time.

**Comment by babbtx** [comment]
I can also update the examples to make that more obvious

**Comment by msgerbush** [comment]
Gotcha, so it's like 'labor cost'.  And yeah, I think we should remove the `ticket_id`.  It will be easier to use, and more consistent.

**Comment by babbtx** [comment]
ok i removed `ticket_id`

**Pull request merged**
